name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Ou o branch que você utiliza para o GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Certifique-se de que a versão Ruby seja compatível com Jekyll

    - name: Install dependencies
      run: bundle install

    - name: Clean _site directory
      run: rm -rf _site

    - name: Build the site with Jekyll
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
